<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="CommWithCamera" Id="{19c51c70-23e6-48e7-b9f9-e1f96618f2f6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM CommWithCamera
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CommWithCamera">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>