<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="CommWithPC" Id="{bac48c79-57e4-4fc5-9e09-7581a510d3e9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM CommWithPC
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CommWithPC">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>