<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{e1b95b3d-d72e-4236-b2e9-ad4cda4ca0ec}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//----------------------------------------程序调用----------------------------------------------
InputLink();
S01_Loading();
S02_LidInjecting();
S03_LidChecking();
S04_AluCovering();
S05_Adjusting();
S06_Cutting();
S07_BoxCarrying();
S08_MainLine();
S09_CardCarrying();
S10_BeltCarrying();
S13_Labeling();
S14_LabelChecking();
S15_NG();


ControlMachine();
CallStandard();
CommWithPC();
CommitWith200SMART();
CommWithCamera();
OutputLink();
LightsTest.LightsTest();



]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="5" />
      <LineId Id="33" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="13" Count="1" />
      <LineId Id="16" Count="0" />
      <LineId Id="23" Count="1" />
      <LineId Id="21" Count="1" />
      <LineId Id="20" Count="0" />
      <LineId Id="17" Count="1" />
      <LineId Id="29" Count="0" />
      <LineId Id="41" Count="1" />
      <LineId Id="19" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="27" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>