<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="S12_PreLine" Id="{ebde0494-312e-4ed1-9c94-463f75f332eb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM S12_PreLine
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[A_Input();
Alarm();
Delay();
FlowAuto();
FlowInit();
General();
ILC();
TipAuto();
TipManual();
Z_Output();]]></ST>
    </Implementation>
    <LineIds Name="S12_PreLine">
      <LineId Id="9" Count="8" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>